# Generated by Django 4.1.7 on 2023-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_alter_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='link',
            field=models.CharField(blank=True, help_text='Link to the lecture', max_length=100),
        ),
    ]
