# Generated by Django 4.1.7 on 2023-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_remove_lecture_date_lecturedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_file',
            field=models.FileField(blank=True, help_text='File of the lecture', null=True, upload_to='uploads/lectures/'),
        ),
    ]
