# Generated by Django 4.1.7 on 2023-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_remove_lecture_lecture_file_lecture_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='filename',
            field=models.CharField(blank=True, help_text='Audio filename of the lecture', max_length=400),
        ),
    ]
