# Generated by Django 4.1.7 on 2023-05-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('lectures', '0008_alter_lecture_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTranscript',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('transcript', models.TextField(blank=True, help_text='Transcript of the lecture')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='LectureDocument',
        ),
    ]
