# Generated by Django 4.1.7 on 2023-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_lecturetranscript_delete_lecturedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='filename',
            field=models.CharField(blank=True, help_text='Audio filename of the lecture', max_length=100),
        ),
        migrations.DeleteModel(
            name='LectureTranscript',
        ),
    ]
