# Generated by Django 4.1.7 on 2023-06-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('lectures', '0010_alter_lecture_filename_delete_lecturetranscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('topic', models.CharField(blank=True, help_text='Topic questioned', max_length=100)),
                ('answer', models.TextField(blank=True, help_text='Q and A')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
