# Generated by Django 4.1.7 on 2023-06-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_alter_question_answer_alter_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='Q and A'),
        ),
    ]
